imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: services.xml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: es
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  asier.ramos.martinez
    password:  L4nb3rr1_S3t4

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
             - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
             - { name: twig.extension }
    twig.extension.cupon:
        class: Eros\FrontendBundle\Twig\Extension\ErosFrontendExtension
        tags:
             - { name: twig.extension }

fos_user:
    db_driver:        orm # can be orm or odm
    firewall_name:    main
    user_class:       Eros\FrontendBundle\Entity\User

sonata_admin:
    title: 'Eros-i'

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific blocks from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

sonata_cache:
    caches:
        esi:
            servers:
                - varnishadm -T 127.0.0.1:2000 {{ COMMAND }} "{{ EXPRESSION }}"

liip_imagine:
    filter_sets:
        thumb_small:
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        thumb_medium:
            filters:
                thumbnail: { size: [150, 120], mode: outbound }
        thumb_frontend:
            quality: 20
            filters:
                thumbnail: { size: [94, 92], mode: outbound }
services:
    acme_hello.twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }
