<?php

namespace Eros\ExtranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecsRepository extends EntityRepository
{
	
}